2024-04-12 15:48:02,862 Minimum price: 10, Maximum price: 350
2024-04-12 15:48:02,874 Preparing sklearn pipeline
2024-04-12 15:48:02,875 Fitting
2024-04-12 15:48:15,375 Scoring
2024-04-12 15:48:15,487 Score: 0.5339406885517419
2024-04-12 15:48:15,487 MAE: 33.565065789473685
2024-04-12 15:48:15,487 Exporting model
/home/kayla/miniconda3/envs/mlflow-d6c04384fb9356865b6d231fc3cbd1b1b9b4863e/lib/python3.9/site-packages/mlflow/models/signature.py:130: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  inputs = _infer_schema(model_input)
[34m[1mwandb[39m[22m: Adding directory to artifact (/tmp/tmpwqenwvq0/random_forest_dir)... Done. 0.0s
Traceback (most recent call last):
  File "/home/kayla/Project-Build-an-ML-Pipeline-Starter/src/train_random_forest/run.py", line 261, in <module>
    train_rf(args)
  File "/home/kayla/Project-Build-an-ML-Pipeline-Starter/src/train_random_forest/run.py", line 111, in train_rf
    fig_feat_imp = plot_feature_importance(sk_pipe, processed_features)
  File "/home/kayla/Project-Build-an-ML-Pipeline-Starter/src/train_random_forest/run.py", line 135, in plot_feature_importance
    ax.set_xticklabels(np.array(feat_names)[::2], rotation=45)  # Adjusted rotation and label selection
  File "/home/kayla/miniconda3/envs/mlflow-d6c04384fb9356865b6d231fc3cbd1b1b9b4863e/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 73, in wrapper
    return get_method(self)(*args, **kwargs)
  File "/home/kayla/miniconda3/envs/mlflow-d6c04384fb9356865b6d231fc3cbd1b1b9b4863e/lib/python3.9/site-packages/matplotlib/axis.py", line 1968, in _set_ticklabels
    return self.set_ticklabels(labels, minor=minor, **kwargs)
  File "/home/kayla/miniconda3/envs/mlflow-d6c04384fb9356865b6d231fc3cbd1b1b9b4863e/lib/python3.9/site-packages/matplotlib/axis.py", line 1890, in set_ticklabels
    raise ValueError(
ValueError: The number of FixedLocator locations (10), usually from a call to set_ticks, does not match the number of ticklabels (6).